### ISSUE TITLE
Summary/description column in profiles table (and column hiding)

### ISSUE THREAD

**Issue by philwareham** [Bloke/smd_thumbnail#15]
Just some thoughts off the top of my head...

It would be nice to have a description field as part of the table row to give a (brief) summary of what the profile is for. Handy if multiple users are creating articles/images for a site.

Also, if their was a column that was designated as permanent, then you could hook the txp-options widget into this plugin for Textopattern 4.7 (in fact, the layout I originally had auto appended a working version of that widget on the table but since you could hide every column it seemed breakable).

I guess the above go hand-in-hand - in that people that don't need the description field can hide the column.

**Comment by Bloke** [comment]
I like the idea of the description column.

And yes, the list options widget should work out of the box because it's supposed to leave one column minimum (the selected column) behind. The trouble with the plugin is that the column headings aren't sortable so the options widget doesn't know which one is currently "active" so therefore you can hide them all.

By adding the ability to sort the table, a local list options will work. The six million dollar question is whether the API is flexible enough to permit filtering by two tables on one page and mix them together in the URL params. It might allow it if the column names are unique. I'll test it.

If not, I might have to introduce my own params, which would probably prevent the list options from working automatically. Hmmm...

**Comment by philwareham** [comment]
The options API worked fine with two tables on the same page. They seemed to be perfectly independent of each other. If you change the class `txp-list--no-options` on your profiles table back to `txp-list` the widget will appear. I may need to adjust some styling though on the table after that.

**Comment by Bloke** [comment]
Okay, I'll add the description column and try out column sorting. That's the main problem. Using the built-in `column_head()` calls, it'll try to sort using the Txp built-in URL params `sort` and `dir`. So if you click one of my table headings, it'll sort by that column fine, but it'll cease sorting the main table. And vice versa: click one of the Txp headings and my table will revert to natural sort order (no columns selected for sorting). 

So this'll mean that whichever table is being sorted, the other table will be able to have all its columns toggled off! It's not really a core problem (as we don't ever have two tables n the same page) but we may be able to do something to "namespace" the sort/dir params. I suspect it'll break stuff though, so it might require custom column toggles. Or maybe I won't bother for now, just add the description column ad worry about sorting another day.

**Comment by philwareham** [comment]
Yeah, maybe just add the description/summary field for now, thanks :)

Didn't realise there were issues with sorting 2 tables on same panel. Might need to address that one day but it can wait.

**Comment by philwareham** [comment]
Tested the description field and works well. Happy to close this issue if column hiding not possible right now.
